name: cubarestapi
description: Flutter plugin for simpler interaction with Cuba's REST API.
version: 0.0.3
author: Sberbank Technology (Roman Sotnichenko)
homepage: https://sber-tech.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  dio: ^3.0.9
  hive: ^1.4.2
  oauth2: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_flutter: ^0.3.1
  test: ^1.14.0
