name: cubarestapi
description: A new flutter plugin for simplier interaction with Cuba's REST API.
version: 0.0.1
author: Sberbank Technology (Roman Sotnichenko)
homepage: https://sber-tech.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.sbrf.cubarestapi
        pluginClass: CubarestapiPlugin
      ios:
        pluginClass: CubarestapiPlugin
